version: 2.1
jobs:
  build:
    working_directory: ~/repo
    docker:
      - image: cimg/node:14.15
    steps:
      - checkout
      - run:
          name: Update NPM
          command: "sudo npm install -g npm"
      - run:
          name: NPM install
          command: "sudo npm install --unsafe-perm"
      - run:
          name: NPM install Gatsby-cli
          command: "sudo npm install -g gatsby-cli"
      - run:
          name: Build
          command: "sudo gatsby build"